# === Key bindings ============================================================

# Reload this configuration file
bind r source-file ~/.tmux.conf \; display "Yep!"

# Open this configuration file in an editor
bind e new-window "vim ~/.tmux.conf"

# Move the focus between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Open a new window or split the active pane
bind c new-window      -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# === General settings ========================================================

setw -g mode-keys vi
set -g default-terminal "screen-256color"
set -g mouse             on
set -g set-titles        on
set -g set-titles-string "[#{session_name}] #{window_name}"
set -g base-index        1
set -g pane-base-index   1

# === Status bar ==============================================================

set -g status-interval              2
set -g status-position              bottom
set -g status-justify               centre
set -g status-bg                    black
set -g status-left                  "  #[fg=magenta]• #S"
set -g status-right                 " #[fg=magenta]• #{b:pane_current_path}  "
set -g window-status-format         "#[fg=white] #W "
set -g window-status-style          dim
set -g window-status-current-format "#[fg=green]• #W "
set -g window-status-current-style  bold

# === Plugins =================================================================

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'timvw/tmux-assistant-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'

# Automatic restore of the last session on start
set -g @continuum-restore 'on'

# === Local overrides =========================================================

if-shell '[ -f ~/.tmux.local.conf ]' 'source-file ~/.tmux.local.conf'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
